name: 'social_media_reporting'
version: '0.2.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  twitter_posts_report: "{{ ref('twitter_organic__tweets') }}"
  facebook_posts_report: "{{ ref('facebook_pages__posts_report') }}"
  linkedin_posts_report: "{{ ref('linkedin_pages__posts') }}"
  instagram_posts_report: "{{ ref('instagram_business__posts') }}"
  social_media_rollup__twitter_enabled: true
  social_media_rollup__facebook_enabled: true
  social_media_rollup__linkedin_enabled: true
  social_media_rollup__instagram_enabled: true

  ##Facebook Pages schema and database variables
  facebook_pages_schema: banfield_facebook_pages
  facebook_pages_database: banfield_facebook_pages

  ##LinkedIn Pages schema and database variables
  linkedin_pages_schema: banfield_linkedin_pages
  linkedin_pages_database: banfield_linkedin_pages

  ##Instagram Business schema and database variables
  instagram_business_schema: banfield_instagram_business
  instagram_business_database: banfield_instagram_business

  ##Twitter Organic schema and database variables
  twitter_organic_schema: banfield_twitter_organic
  twitter_organic_database: banfieldtwitter_organic
models:
  social_media_reporting:
    +schema: social_media_reporting
    +materialized: table
